//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp.SW {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kya.by/", ConfigurationName="SW.KYAServicesSoap")]
    public interface KYAServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Sum", ReplyAction="*")]
        int Sum(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Sum", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SumAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Mul", ReplyAction="*")]
        int Mul(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulAsync(int x, int y);
        
        // CODEGEN: Контракт генерации сообщений с именем x из пространства имен http://kya.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Add", ReplyAction="*")]
        WindowsFormsApp.SW.AddResponse Add(WindowsFormsApp.SW.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp.SW.AddResponse> AddAsync(WindowsFormsApp.SW.AddRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetResult из пространства имен http://kya.by/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Get", ReplyAction="*")]
        WindowsFormsApp.SW.GetResponse Get(WindowsFormsApp.SW.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kya.by/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp.SW.GetResponse> GetAsync(WindowsFormsApp.SW.GetRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://kya.by/", Order=0)]
        public WindowsFormsApp.SW.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(WindowsFormsApp.SW.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kya.by/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(string x) {
            this.x = x;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://kya.by/", Order=0)]
        public WindowsFormsApp.SW.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(WindowsFormsApp.SW.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddResponseBody {
        
        public AddResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get", Namespace="http://kya.by/", Order=0)]
        public WindowsFormsApp.SW.GetRequestBody Body;
        
        public GetRequest() {
        }
        
        public GetRequest(WindowsFormsApp.SW.GetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetRequestBody {
        
        public GetRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetResponse", Namespace="http://kya.by/", Order=0)]
        public WindowsFormsApp.SW.GetResponseBody Body;
        
        public GetResponse() {
        }
        
        public GetResponse(WindowsFormsApp.SW.GetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kya.by/")]
    public partial class GetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetResult;
        
        public GetResponseBody() {
        }
        
        public GetResponseBody(string GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KYAServicesSoapChannel : WindowsFormsApp.SW.KYAServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KYAServicesSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp.SW.KYAServicesSoap>, WindowsFormsApp.SW.KYAServicesSoap {
        
        public KYAServicesSoapClient() {
        }
        
        public KYAServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KYAServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KYAServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KYAServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Sum(int x, int y) {
            return base.Channel.Sum(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SumAsync(int x, int y) {
            return base.Channel.SumAsync(x, y);
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int x, int y) {
            return base.Channel.SubAsync(x, y);
        }
        
        public int Mul(int x, int y) {
            return base.Channel.Mul(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int x, int y) {
            return base.Channel.MulAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp.SW.AddResponse WindowsFormsApp.SW.KYAServicesSoap.Add(WindowsFormsApp.SW.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public void Add(string x) {
            WindowsFormsApp.SW.AddRequest inValue = new WindowsFormsApp.SW.AddRequest();
            inValue.Body = new WindowsFormsApp.SW.AddRequestBody();
            inValue.Body.x = x;
            WindowsFormsApp.SW.AddResponse retVal = ((WindowsFormsApp.SW.KYAServicesSoap)(this)).Add(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp.SW.AddResponse> WindowsFormsApp.SW.KYAServicesSoap.AddAsync(WindowsFormsApp.SW.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp.SW.AddResponse> AddAsync(string x) {
            WindowsFormsApp.SW.AddRequest inValue = new WindowsFormsApp.SW.AddRequest();
            inValue.Body = new WindowsFormsApp.SW.AddRequestBody();
            inValue.Body.x = x;
            return ((WindowsFormsApp.SW.KYAServicesSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp.SW.GetResponse WindowsFormsApp.SW.KYAServicesSoap.Get(WindowsFormsApp.SW.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public string Get() {
            WindowsFormsApp.SW.GetRequest inValue = new WindowsFormsApp.SW.GetRequest();
            inValue.Body = new WindowsFormsApp.SW.GetRequestBody();
            WindowsFormsApp.SW.GetResponse retVal = ((WindowsFormsApp.SW.KYAServicesSoap)(this)).Get(inValue);
            return retVal.Body.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp.SW.GetResponse> WindowsFormsApp.SW.KYAServicesSoap.GetAsync(WindowsFormsApp.SW.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp.SW.GetResponse> GetAsync() {
            WindowsFormsApp.SW.GetRequest inValue = new WindowsFormsApp.SW.GetRequest();
            inValue.Body = new WindowsFormsApp.SW.GetRequestBody();
            return ((WindowsFormsApp.SW.KYAServicesSoap)(this)).GetAsync(inValue);
        }
    }
}
